apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: blockid
  name: blockid
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blockid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blockid
    spec:
      containers:
        - name: blockid
          image: 293637174735.dkr.ecr.us-east-1.amazonaws.com/blockid:latest
          ports:
            - name: blocksid-charlie
              containerPort: 40335
              protocol: TCP
            - name: ws-port
              containerPort: 8846
              protocol: TCP
            - name: wasm-port
              containerPort: 30345
              protocol: TCP
            - name: wasm-ws-port
              containerPort: 9979
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
         
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
